language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t evertonluperes/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true evertonluperes/docker-react npm run test
